In [1]:
pip install fitz

Collecting fitz
  Downloading fitz-0.0.1.dev2-py2.py3-none-any.whl (20 kB)
Collecting configobj
  Downloading configobj-5.0.8-py2.py3-none-any.whl (36 kB)
Collecting configparser
  Downloading configparser-5.3.0-py3-none-any.whl (19 kB)
Requirement already satisfied: pandas in c:\anaconda3\lib\site-packages (from fitz) (1.2.4)
Collecting pyxnat
  Downloading pyxnat-1.5-py3-none-any.whl (95 kB)
Requirement already satisfied: numpy in c:\anaconda3\lib\site-packages (from fitz) (1.20.1)
Collecting nibabel
  Downloading nibabel-5.0.1-py3-none-any.whl (3.3 MB)
Collecting nipype
  Downloading nipype-1.8.5-py3-none-any.whl (3.2 MB)
Requirement already satisfied: scipy in c:\anaconda3\lib\site-packages (from fitz) (1.6.2)
Collecting httplib2
  Downloading httplib2-0.22.0-py3-none-any.whl (96 kB)
Requirement already satisfied: six in c:\anaconda3\lib\site-packages (from configobj->fitz) (1.15.0)
Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in c:\anaconda3\lib\site-packages (from httplib2->fitz) (2.4.7)
Requirement already satisfied: packaging>=17 in c:\anaconda3\lib\site-packages (from nibabel->fitz) (20.9)
Requirement already satisfied: setuptools in c:\anaconda3\lib\site-packages (from nibabel->fitz) (52.0.0.post20210125)
Collecting simplejson>=3.8.0
  Downloading simplejson-3.18.4-cp38-cp38-win_amd64.whl (74 kB)
Requirement already satisfied: click>=6.6.0 in c:\anaconda3\lib\site-packages (from nipype->fitz) (7.1.2)
Requirement already satisfied: filelock>=3.0.0 in c:\anaconda3\lib\site-packages (from nipype->fitz) (3.0.12)
Collecting traits!=5.0,<6.4,>=4.6
  Downloading traits-6.3.2-cp38-cp38-win_amd64.whl (5.0 MB)
Collecting rdflib>=5.0.0
  Downloading rdflib-6.3.1-py3-none-any.whl (527 kB)
Requirement already satisfied: networkx>=2.0 in c:\anaconda3\lib\site-packages (from nipype->fitz) (2.5)
Collecting etelemetry>=0.2.0
  Downloading etelemetry-0.3.0-py3-none-any.whl (6.3 kB)
Requirement already satisfied: python-dateutil>=2.2 in c:\anaconda3\lib\site-packages (from nipype->fitz) (2.8.1)
Collecting pydot>=1.2.3
  Downloading pydot-1.4.2-py2.py3-none-any.whl (21 kB)
Collecting looseversion
  Downloading looseversion-1.1.2-py3-none-any.whl (8.1 kB)
Collecting prov>=1.5.2
  Downloading prov-2.0.0-py3-none-any.whl (421 kB)
Requirement already satisfied: requests in c:\anaconda3\lib\site-packages (from etelemetry>=0.2.0->nipype->fitz) (2.25.1)
Collecting ci-info>=0.2
  Downloading ci_info-0.3.0-py3-none-any.whl (7.8 kB)
Requirement already satisfied: decorator>=4.3.0 in c:\anaconda3\lib\site-packages (from networkx>=2.0->nipype->fitz) (5.0.6)
Requirement already satisfied: lxml>=3.3.5 in c:\anaconda3\lib\site-packages (from prov>=1.5.2->nipype->fitz) (4.6.3)
Collecting isodate<0.7.0,>=0.6.0
  Downloading isodate-0.6.1-py2.py3-none-any.whl (41 kB)
Requirement already satisfied: pytz>=2017.3 in c:\anaconda3\lib\site-packages (from pandas->fitz) (2021.1)
Requirement already satisfied: future>=0.16 in c:\anaconda3\lib\site-packages (from pyxnat->fitz) (0.18.2)
Collecting pathlib>=1.0
  Downloading pathlib-1.0.1-py3-none-any.whl (14 kB)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\anaconda3\lib\site-packages (from requests->etelemetry>=0.2.0->nipype->fitz) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in c:\anaconda3\lib\site-packages (from requests->etelemetry>=0.2.0->nipype->fitz) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\anaconda3\lib\site-packages (from requests->etelemetry>=0.2.0->nipype->fitz) (1.26.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\anaconda3\lib\site-packages (from requests->etelemetry>=0.2.0->nipype->fitz) (2020.12.5)
Installing collected packages: isodate, rdflib, ci-info, traits, simplejson, pydot, prov, pathlib, nibabel, looseversion, etelemetry, pyxnat, nipype, httplib2, configparser, configobj, fitz
Successfully installed ci-info-0.3.0 configobj-5.0.8 configparser-5.3.0 etelemetry-0.3.0 fitz-0.0.1.dev2 httplib2-0.22.0 isodate-0.6.1 looseversion-1.1.2 nibabel-5.0.1 nipype-1.8.5 pathlib-1.0.1 prov-2.0.0 pydot-1.4.2 pyxnat-1.5 rdflib-6.3.1 simplejson-3.18.4 traits-6.3.2
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install PyMuPDF

Collecting PyMuPDF
  Downloading PyMuPDF-1.21.1-cp38-cp38-win_amd64.whl (11.7 MB)
Installing collected packages: PyMuPDF
Successfully installed PyMuPDF-1.21.1
Note: you may need to restart the kernel to use updated packages.

In [1]:
import fitz
import pandas as pd
import io
import glob

In [2]:
# загрузка в list пути всех нужных pdf файлов
all_pdf = glob.glob(r"PDF\*.pdf")

In [3]:
len(all_pdf)

10

In [4]:
all_pdf

['PDF\\PDF1.pdf',
 'PDF\\PDF10.pdf',
 'PDF\\PDF2.pdf',
 'PDF\\PDF3.pdf',
 'PDF\\PDF4.pdf',
 'PDF\\PDF5.pdf',
 'PDF\\PDF6.pdf',
 'PDF\\PDF7.pdf',
 'PDF\\PDF8.pdf',
 'PDF\\PDF9.pdf']

In [22]:
pdf_document = r"/PDF"
doc = fitz.open(pdf_document)
print("Исходный документ: ", doc)
print("\nКоличество страниц: %i\n\n------------------\n\n" % doc.page_count)
print(doc.metadata)
for current_page in range(len(doc)):
    page = doc.load_page(current_page)
    page_text = page.get_text("text")
    print("Стр. ", current_page+1, "\n")
    print(page_text)

FileNotFoundError: no such file: '/PDF'

In [ ]:
pdf_document = r"PDF"
doc = fitz.open(pdf_document)
print("Исходный документ: ", doc)
text = []
for current_page in range(len(doc)):
    page = doc.load_page(current_page)
    page_text = page.get_text("text")
    text.append(page_text)
    print(page_text)

In [ ]:
text = ''.join(text).replace('\n',' ')

In [6]:
text

NameError: name 'text' is not defined

In [ ]:
def extract_text_from_pdf(pdf):
    doc = fitz.open(pdf)
    text = []
    for current_page in range(len(doc)):
        page = doc.load_page(current_page)
        page_text = page.get_text("text")
        text.append(page_text)
    return text

In [ ]:
def pars_pdf(text):
    text2 = text.split('\n')
    print(text2)
    if 'Общий рейтинг' in text2:
        num = text2.index('Общий рейтинг')
        raiting = text2[num-1]
        name = text2[num+1]
        activity = text2[num+2]
        date_publish = ""
        print(num, raiting, name, activity, date_publish)
        
    else:
        raiting = 0
        name = ""
        activity = ""
        
        print(num, raiting, name, activity, date_publish)
    
    return  name, raiting, activity, date_publish

In [ ]:
x = extract_text_from_pdf(r"PDF\habr1.pdf")

In [ ]:
x

In [ ]:
pars_pdf(x[0])

In [7]:
# Перебор текста из pdf файла, парсинг
Brak = []
NameCompany = []
Description = []
Raiting = []
DataPublish = []
Activity = []
TextArticle = []
for pdf_path in all_pdf:
    try:  
        text_content  = extract_text_from_pdf(pdf_path)
        filename = pdf_path.split('\\')[-1]
        print(filename)
        N, R, A, D = pars_pdf(text_content[0])
        print(N, R, A, D)
        T = ' '.join(text_content).replace('\n', ' ').strip()
        NameCompany.append(N)
        Raiting.append(R)
        DataPublish.append(D)
        Activity.append(A)
        TextArticle.append(T)
    except:
        Brak.append(pdf_path)

In [8]:
Brak

['PDF\\PDF1.pdf',
 'PDF\\PDF10.pdf',
 'PDF\\PDF2.pdf',
 'PDF\\PDF3.pdf',
 'PDF\\PDF4.pdf',
 'PDF\\PDF5.pdf',
 'PDF\\PDF6.pdf',
 'PDF\\PDF7.pdf',
 'PDF\\PDF8.pdf',
 'PDF\\PDF9.pdf']

In [9]:
# Создание DataFrame
df = pd.DataFrame({
'NameCompany': [],
'Description': [],
'Raiting': [],
'DataPublish': [],
'Activity': [],
'TextArticle': []
})

In [10]:
df

Empty DataFrame
Columns: [NameCompany, Description, Raiting, DataPublish, Activity, TextArticle]
Index: []

In [11]:
print(len(NameCompany), len(Description), len(Raiting), len(DataPublish),len(Activity), len(TextArticle) )

0 0 0 0 0 0

In [12]:
NameCompany

[]

In [13]:
df['NameCompany'] = NameCompany

In [14]:
df['Raiting'] = Raiting

In [15]:
df['DataPublish'] = DataPublish

In [16]:
df['Activity'] = Activity

In [17]:
df['TextArticle'] = TextArticle

In [18]:
df

Empty DataFrame
Columns: [NameCompany, Description, Raiting, DataPublish, Activity, TextArticle]
Index: []

In [19]:
import pandas
df.to_csv(r"dataset.csv")

In [20]:
df2 = pd.read_csv(r"dataset.csv")
df2.head()

Empty DataFrame
Columns: [Unnamed: 0, NameCompany, Description, Raiting, DataPublish, Activity, TextArticle]
Index: []